<a href="https://colab.research.google.com/github/denomite/PortfolioProjects/blob/main/PyTorchIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

LISTS

In [ ]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

NUMPY ARRAYS

In [ ]:
np1 = np.random.rand(3, 4)
np1

array([[0.02094511, 0.51403487, 0.28789423, 0.91693731],
       [0.44011773, 0.47733174, 0.81772295, 0.54551649],
       [0.27202691, 0.47113638, 0.06635378, 0.72123024]])

In [ ]:
np1.dtype

dtype('float64')

TENSORS

In [ ]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.8935,  1.4876,  0.6526, -1.7430],
        [-0.4495, -0.5707,  0.2280, -0.7475],
        [ 1.8853, -0.5055, -1.0115, -0.2111]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0209, 0.5140, 0.2879, 0.9169],
        [0.4401, 0.4773, 0.8177, 0.5455],
        [0.2720, 0.4711, 0.0664, 0.7212]], dtype=torch.float64)